version: '3.1'

services:
  db_backup:
      image: arizalsaputro/mongo-gcs-backup
      environment:
        - MONGODB_HOST=yourmongodbhost
        - MONGODB_PORT=yourmongodbport
        - MONGODB_DB=yourmongodbdatabase
        - CRON_EXPRESSION=59 23 * * *
        - GCS_KEY_FILE_PATH=/your-path-of/service-account.json
        - GCS_BUCKET=gs://yourname-of-bucket
        - SLACK_ALERTS=true
        - SLACK_WEBHOOK_URL=https://your-slack-webhook-url
        - SLACK_CHANNEL=#yourchannelorusername
      secrets:
        - service_account
secrets:
  service_account:
    file: service_account.json